[package]
name = "cssparser_lib"
version = "0.1.0"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
cssparser = { git = "https://github.com/servo/rust-cssparser.git" }
